version: '3.7'

services:

  rabbit:
    container_name: rabbit
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    ports:
      - 9091:9091
